name: Android Pull Request CI

on:
  pull_request:
    branches: [ develop, ci ]

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        env:
          DEBUG_KEYSTORE: ${{ secrets.DEBUG_KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES }}
        run: |
          echo "$KEYSTORE" | base64 -d > ./app/boolti-keystore.keystore
          echo "$KEYSTORE_PROPERTIES" > keystore.properties
          echo "$LOCAL_PROPERTIES" > local.properties
          echo "$GOOGLE_SERVICES" > ./app/google-services.json
          ./gradlew test --stacktrace

      - name: Publish Test Results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "**/test-results/**/*.xml"
